//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace _23_04_2020.Translator {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="Translator.IService1")]
    public interface IService1 {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/AddNewWord_WordTranslate", ReplyAction="http://tempuri.org/IService1/AddNewWord_WordTranslateResponse")]
        void AddNewWord_WordTranslate(string word, string wordTranslate);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/AddNewWord_WordTranslate", ReplyAction="http://tempuri.org/IService1/AddNewWord_WordTranslateResponse")]
        System.Threading.Tasks.Task AddNewWord_WordTranslateAsync(string word, string wordTranslate);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/GetTranslationsWords", ReplyAction="http://tempuri.org/IService1/GetTranslationsWordsResponse")]
        string[] GetTranslationsWords(string word);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/GetTranslationsWords", ReplyAction="http://tempuri.org/IService1/GetTranslationsWordsResponse")]
        System.Threading.Tasks.Task<string[]> GetTranslationsWordsAsync(string word);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IService1Channel : _23_04_2020.Translator.IService1, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class Service1Client : System.ServiceModel.ClientBase<_23_04_2020.Translator.IService1>, _23_04_2020.Translator.IService1 {
        
        public Service1Client() {
        }
        
        public Service1Client(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public Service1Client(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public Service1Client(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public Service1Client(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public void AddNewWord_WordTranslate(string word, string wordTranslate) {
            base.Channel.AddNewWord_WordTranslate(word, wordTranslate);
        }
        
        public System.Threading.Tasks.Task AddNewWord_WordTranslateAsync(string word, string wordTranslate) {
            return base.Channel.AddNewWord_WordTranslateAsync(word, wordTranslate);
        }
        
        public string[] GetTranslationsWords(string word) {
            return base.Channel.GetTranslationsWords(word);
        }
        
        public System.Threading.Tasks.Task<string[]> GetTranslationsWordsAsync(string word) {
            return base.Channel.GetTranslationsWordsAsync(word);
        }
    }
}
