//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ChatWindow.ServiceReference1 {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="ServiceReference1.IGame", CallbackContract=typeof(ChatWindow.ServiceReference1.IGameCallback))]
    public interface IGame {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IGame/Login", ReplyAction="http://tempuri.org/IGame/LoginResponse")]
        string[] Login(string name);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IGame/Login", ReplyAction="http://tempuri.org/IGame/LoginResponse")]
        System.Threading.Tasks.Task<string[]> LoginAsync(string name);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IGame/StartGame", ReplyAction="http://tempuri.org/IGame/StartGameResponse")]
        void StartGame(string PlayerName, string nameToGame);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IGame/StartGame", ReplyAction="http://tempuri.org/IGame/StartGameResponse")]
        System.Threading.Tasks.Task StartGameAsync(string PlayerName, string nameToGame);
        
        [System.ServiceModel.OperationContractAttribute(IsOneWay=true, Action="http://tempuri.org/IGame/PlayerMove")]
        void PlayerMove(string userName, int x, int y);
        
        [System.ServiceModel.OperationContractAttribute(IsOneWay=true, Action="http://tempuri.org/IGame/PlayerMove")]
        System.Threading.Tasks.Task PlayerMoveAsync(string userName, int x, int y);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IGame/Logout", ReplyAction="http://tempuri.org/IGame/LogoutResponse")]
        void Logout(string name);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IGame/Logout", ReplyAction="http://tempuri.org/IGame/LogoutResponse")]
        System.Threading.Tasks.Task LogoutAsync(string name);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IGame/EndGame", ReplyAction="http://tempuri.org/IGame/EndGameResponse")]
        void EndGame(string name);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IGame/EndGame", ReplyAction="http://tempuri.org/IGame/EndGameResponse")]
        System.Threading.Tasks.Task EndGameAsync(string name);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IGameCallback {
        
        [System.ServiceModel.OperationContractAttribute(IsOneWay=true, Action="http://tempuri.org/IGame/CallbackGetNewPalyers")]
        void CallbackGetNewPalyers(string[] msg);
        
        [System.ServiceModel.OperationContractAttribute(IsOneWay=true, Action="http://tempuri.org/IGame/CallbackGameSuccessfulEnded")]
        void CallbackGameSuccessfulEnded(bool isWin);
        
        [System.ServiceModel.OperationContractAttribute(IsOneWay=true, Action="http://tempuri.org/IGame/CallbackGetServerPlayingField")]
        void CallbackGetServerPlayingField(System.Nullable<bool>[][] msg);
        
        [System.ServiceModel.OperationContractAttribute(IsOneWay=true, Action="http://tempuri.org/IGame/CallbackGameStarted")]
        void CallbackGameStarted(bool msg);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IGameChannel : ChatWindow.ServiceReference1.IGame, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class GameClient : System.ServiceModel.DuplexClientBase<ChatWindow.ServiceReference1.IGame>, ChatWindow.ServiceReference1.IGame {
        
        public GameClient(System.ServiceModel.InstanceContext callbackInstance) : 
                base(callbackInstance) {
        }
        
        public GameClient(System.ServiceModel.InstanceContext callbackInstance, string endpointConfigurationName) : 
                base(callbackInstance, endpointConfigurationName) {
        }
        
        public GameClient(System.ServiceModel.InstanceContext callbackInstance, string endpointConfigurationName, string remoteAddress) : 
                base(callbackInstance, endpointConfigurationName, remoteAddress) {
        }
        
        public GameClient(System.ServiceModel.InstanceContext callbackInstance, string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(callbackInstance, endpointConfigurationName, remoteAddress) {
        }
        
        public GameClient(System.ServiceModel.InstanceContext callbackInstance, System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(callbackInstance, binding, remoteAddress) {
        }
        
        public string[] Login(string name) {
            return base.Channel.Login(name);
        }
        
        public System.Threading.Tasks.Task<string[]> LoginAsync(string name) {
            return base.Channel.LoginAsync(name);
        }
        
        public void StartGame(string PlayerName, string nameToGame) {
            base.Channel.StartGame(PlayerName, nameToGame);
        }
        
        public System.Threading.Tasks.Task StartGameAsync(string PlayerName, string nameToGame) {
            return base.Channel.StartGameAsync(PlayerName, nameToGame);
        }
        
        public void PlayerMove(string userName, int x, int y) {
            base.Channel.PlayerMove(userName, x, y);
        }
        
        public System.Threading.Tasks.Task PlayerMoveAsync(string userName, int x, int y) {
            return base.Channel.PlayerMoveAsync(userName, x, y);
        }
        
        public void Logout(string name) {
            base.Channel.Logout(name);
        }
        
        public System.Threading.Tasks.Task LogoutAsync(string name) {
            return base.Channel.LogoutAsync(name);
        }
        
        public void EndGame(string name) {
            base.Channel.EndGame(name);
        }
        
        public System.Threading.Tasks.Task EndGameAsync(string name) {
            return base.Channel.EndGameAsync(name);
        }
    }
}
